apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: jrodriguez0/bookstoreproject-2:order-service
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"

            - name: SERVER_PORT
              value: "8082"

            # ✔ Base de datos CORRECTA
            - name: DB_URL
              value: "jdbc:mysql://mysql-db:3306/orderdb"

            - name: DB_USER
              value: "bookstore"
            - name: DB_PASSWORD
              value: "bookstore123"

            # ✔ gRPC hacia carrito
            - name: CART_GRPC_HOST
              value: "cart-service"
            - name: CART_GRPC_PORT
              value: "9091"

            # ✔ RabbitMQ centralizado
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: "bookstore"
            - name: RABBITMQ_PASS
              value: "bookstore123"