apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: jrodriguez0/bookstoreproject-2:catalog-service
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SERVER_PORT
              value: "8080"

            # MYSQL
            - name: DB_URL
              value: jdbc:mysql://mysql-db:3306/catalogdb
            - name: DB_USER
              value: bookstore
            - name: DB_PASSWORD
              value: bookstore123

            # gRPC
            - name: GRPC_SERVER_PORT
              value: "9090"

            # RABBITMQ
            - name: RABBITMQ_HOST
              value: rabbitmq-service
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: bookstore
            - name: RABBITMQ_PASS
              value: bookstore123
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: catalog