apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: jrodriguez0/bookstoreproject-2:catalog-service
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: grpc
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SERVER_PORT
              value: "8080"
            - name: DB_URL
              value: "jdbc:mysql://mysql-db:3306/catalogdb"
            - name: DB_USER
              value: "bookstore"
            - name: DB_PASSWORD
              value: "bookstore123"
            - name: GRPC_SERVER_PORT
              value: "9090"
          
          resources:
            requests:
              memory: "640Mi"
              cpu: "400m"
            limits:
              memory: "1280Mi"
              cpu: "800m"