server:
  port: 8081

spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:mysql://mysql-db:3306/cartdb
    username: bookstore
    password: bookstore123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:bookstore}
    password: ${RABBITMQ_PASS:bookstore123}

grpc:
  client:
    catalog-service:
      address: static://catalog-service:9090
      negotiationType: plaintext

logging:
  level:
    root: INFO
    com.bookstore.cart_service: DEBUG