apiVersion: apps/v1
kind: Deployment
metadata:
  name: review
  labels:
    app: review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
        - name: review
          image: jrodriguez0/bookstore-project:review-service
          ports:
            - containerPort: 5002
          env:
            - name: FLASK_ENV
              value: "production"
            - name: PORT
              value: "5002"
            - name: DATABASE_URL
              value: "mysql://bookstore:bookstore123@mysql-db:3306/review_db" # Ajustar al formato de URL que use tu app Flask/Python
            - name: USER_SERVICE_URL
              value: "http://user-service:8083"
            - name: JWT_SECRET
              value: "bookstore-jwt-secret-key-change-in-production"
            - name: RABBITMQ_HOST
              value: "rabbitmq-review-svc"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: "bookstore"
            - name: RABBITMQ_PASS
              value: "bookstore123"