apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: jrodriguez0/bookstoreproject-2:cart-service
          ports:
            - containerPort: 8081
              name: http
            - containerPort: 9091
              name: grpc
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SERVER_PORT
              value: "8081"
            - name: GRPC_SERVER_PORT
              value: "9091"
            - name: DB_URL
              value: "jdbc:mysql://mysql-db:3306/cartdb"
            - name: DB_USER
              value: "bookstore"
            - name: DB_PASSWORD
              value: "bookstore123"
            - name: CATALOG_GRPC_HOST
              value: "catalog-service"
            - name: CATALOG_GRPC_PORT
              value: "9090"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: "bookstore"
            - name: RABBITMQ_PASS
              value: "bookstore123"
          resources:
            requests:
              memory: "640Mi"
              cpu: "400m"
            limits:
              memory: "1280Mi"
              cpu: "800m"