apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: santi1221/bookstore-tet:user-service
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-db:3306/userdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "bookstore"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "bookstore123"
            - name: DATABASE_URL
              value: "jdbc:mysql://mysql-db:3306/userdb"
            - name: DB_USER
              value: "bookstore"
            - name: DB_PASSWORD
              value: "bookstore123"
            - name: RABBITMQ_HOST
              value: "rabbitmq-user-svc"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: "bookstore"
            - name: RABBITMQ_PASS
              value: "bookstore123"